In [1]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({
        "이름" : ["민수", "지영"],
        "점수" : [90, 85]
})

display(df1)

  이름  점수
0     90
1     85

In [7]:
df2 = pd.DataFrame([
    ["민수", 90],
    ["지영", 85],
], index = ["첫번째", "두번째"], columns= ["이름", "점수"])

df2

     이름  점수
첫번째  민수  90
두번째  지영  85

In [10]:
df3 = pd.DataFrame([
    {"이름" : "민수", "점수": 90},
    {"이름" : "지영", "저음수": 100},

])
df3

   이름    점수    저음수
0  민수  90.0    NaN
1  지영   NaN  100.0

In [11]:
import numpy as np

df4 = pd.DataFrame(np.array([
    [1, 2], [3, 4]
]), columns = ["x", "y"])

df4

   x  y
0  1  2
1  3  4

In [12]:
# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

print(df)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [13]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
df.values

array([['철수', 20, '남'],
       ['영희', 21, '여'],
       ['민수', 20, '남'],
       ['지영', 22, '여'],
       ['준호', 21, '남']], dtype=object)

In [15]:
df.dtypes

이름      str
나이    int64
성별      str
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [18]:
df["성별"].unique()

<StringArray>
['남', '여']
Length: 2, dtype: str